### ISSUE TITLE
Writing an extension

### ISSUE THREAD

**Issue by talsafran** [jessepollak/slash#7]
i want to make a thing that lets you type in all lower case:

> lazy typers are still people too. let's help them look dignified in their emails and make the world a better place. am i right?

and then you type in `/caps`

and it takes your entire textbox and properly capitalizes it:

> Lazy typers are still people too. Let's help them look dignified in their emails and make the world a better place. Am I right?

---

I haven't dug into the source yet to figure out if I can write this extension, but it'd be helpful to have some pointers / best practices / etc.

**Comment by bsiddiqui** [comment]
@talsafran that would be :100:

**Comment by jessepollak** [comment]
Woo! I'm so thrilled to see that other people are excited about writing an extension (which I want to call a `command`, even though it's shares the name of the project). 

Some thoughts:
1. Right now, commands are written as React components. Ultimately, I don't think this is the best model for building an extensible command platform, but when I started it was the easiest mental model. This command-as-React-component doesn't really vibe with what you're trying to do, which is apply a transform to the field, rather than pop up a Component, which allows the user to do something _then_ apply a transform to the field. 
2. I've previously hacked around my self-imposed component-as-React-component model by defining a React component that essentially does nothing. You can check that out in the [Help command](https://github.com/jessepollak/command/blob/master/src/components/commands/Help/Help.jsx#L8). It opens up a new window, then kills itself.
3. I'd like to transition away from the command-as-React-component model to something much more flexible — essentially I want commands to export an object with a set of consistent properties, then provide helpers to make doing things like mounting a React component very easy.

I haven't yet defined what this more extensible format is, but I'm going to try and do that in the next couple days. Here's the basic gist of what I think we need:
- `mount` - A function that the command exports that "mounts" it when the user selects it. This "mounting" could be rendering a React component, redirecting the window, applying a transform to the field, or anything else — I think the key is to leave this very flexible. Right now, I think this `mount` function should be called with two arguments:
  - `field` — a [Field](https://github.com/jessepollak/command/blob/master/src/fields/Field.js) object (or the appropriate subclass) that represents the `textarea` or `div[contenteditable="true"]` field that the user is currently typing in.
  - `onDone` — a callback that the command should call when it's done processing. This `onDone` function should optionally take a generic [Type](https://github.com/jessepollak/command/tree/master/src/types), which we can use to provide an easy way to do common things (like insert an image or redirect the page).*
- `match` - A string which is the name of the `/command`
- `icon` - A required image that serves as the icon for the command in the quick dropdown.

I think with that API, and the right abstractions, we can leave things pretty flexible, while still providing the tools to make adding a new command pretty easy.

Thoughts?
- One question I have here is whether we should have a `Type.Transform` here or whether we should allow commands to apply transforms in their `mount` function on the `field` argument and then call `onDone` with no return value. I'm not sure what's better — maybe allowing both is OK.

**Comment by jessepollak** [comment]
OK, went ahead and made a bunch of the changes that bring this closer, check out the CONTRIBUTING.md file here: https://github.com/jessepollak/command/blob/master/CONTRIBUTING.md

**Comment by talsafran** [comment]
Thanks @jessepollak
